data_dir : /home/amisery/SemesterProject/out_cap_1000.h5

# num_devices : 3
devices_names : [1]
batch_size : 512
ckpt_path : "./tb_logs/my_model/version_9/checkpoints/epoch=47-step=10128.ckpt"
tasks : ["test"]
engine:
  model_kwargs:
    d_model : 128
    d_ff: 64
    num_heads : 2
    num_layers : 6 
    in_features : 4 
    out_features : 3

  lr : 2.0e-3
  use_weighted_loss : True

trainer_config:
  max_epochs : 100
  accumulate_grad_batches : 5
  strategy : auto
  deterministic : False
  log_every_n_steps : 10

