data_dir : /scratch/.amisery/out_cap_1000.h5

# num_devices : 3
devices_names : [3,4,5,6]
batch_size : 64
tasks : ["fit","test"]

engine:
  model_kwargs:
    d_model : 256
    d_ff: 64
    num_heads : 4
    num_layers : 6 
    in_features : 4 
    out_features : 3

  lr : 1.0e-3
  use_weighted_loss : True

trainer_config:
  max_epochs : 100
  accumulate_grad_batches : 5
  strategy : auto
  deterministic : False
  log_every_n_steps : 10

