data_dir : /scratch/.amisery/out_cap_1000.h5

# num_devices : 3
devices_names : [2,4,5,6]
batch_size : 32
tasks : ["fit","test"]

engine:
  model_name : "v0"
  model_kwargs:
    d_ff: 64
    d_model: 128
    in_features: 4
    num_heads: 2
    num_layers: 8
    out_features: 3
    emb_type : "mlp"

  lr : 1.0e-3
  weight : [2.5,1,1.5]
  use_weighted_loss : False

trainer_config:
  max_epochs : 50
  accumulate_grad_batches : 5
  strategy : auto
  deterministic : False
  log_every_n_steps : 10
  
  

